//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Banco_De_Sangre
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolsas
    {
        public int Id { get; set; }
        public int TipoBolsa { get; set; }
        public int Cantidadml { get; set; }
        public int Donante { get; set; }
        public int Receptor { get; set; }
        public System.DateTime FechaDonacion { get; set; }
        public Nullable<System.DateTime> FechaAplicacion { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual TipoBolsa TipoBolsa1 { get; set; }
        public virtual Paciente Paciente1 { get; set; }
    }
}
