//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Banco_De_Sangre
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaseGestionBDSEntitiesConect : DbContext
    {
        public BaseGestionBDSEntitiesConect()
            : base("name=BaseGestionBDSEntitiesConect")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolsas> Bolsas { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoBolsa> TipoBolsa { get; set; }
        public virtual DbSet<TipoRH> TipoRH { get; set; }
        public virtual DbSet<TipoSangre> TipoSangre { get; set; }
    }
}
