USE master
GO

--ELIMINA LA BASE DE DATOS SI YA EXISTE

IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = 'BaseGestionBDS')
BEGIN
	ALTER DATABASE [BaseGestionBDS] SET OFFLINE WITH ROLLBACK IMMEDIATE;
	ALTER DATABASE [BaseGestionBDS] SET ONLINE;
	DROP DATABASE [BaseGestionBDS];
END

GO

--CREANDO LA BASE DE DATOS

CREATE DATABASE BaseGestionBDS
GO

USE BaseGestionBDS
GO

--TABLA TIPOS DE SANGRE

DROP TABLE IF EXISTS TipoSangre;
CREATE TABLE TipoSangre
(
Id INT IDENTITY NOT NULL,
NombreTS TEXT NOT NULL

PRIMARY KEY (Id)
);

INSERT INTO TipoSangre(NombreTS) VALUES ('AB');
INSERT INTO TipoSangre(NombreTS) VALUES ('A');
INSERT INTO TipoSangre(NombreTS) VALUES ('B');
INSERT INTO TipoSangre(NombreTS) VALUES ('O');

--TABLA TIPOS DE RH

DROP TABLE IF EXISTS TipoRH;
CREATE TABLE TipoRH
(
Id INT IDENTITY NOT NULL,
NombreRH TEXT NOT NULL

PRIMARY KEY (Id)
);

INSERT INTO TipoRH(NombreRH) VALUES ('Positivo');
INSERT INTO TipoRH(NombreRH) VALUES ('Negativo');

--TABLA GÉNERO

DROP TABLE IF EXISTS Genero;
CREATE TABLE Genero
(
Id INT IDENTITY NOT NULL,
NombreGenero TEXT NOT NULL

PRIMARY KEY (Id)
);

INSERT INTO Genero(NombreGenero) VALUES ('Masculino');
INSERT INTO Genero(NombreGenero) VALUES ('Femenino');
INSERT INTO Genero(NombreGenero) VALUES ('Otro');
INSERT INTO Genero(NombreGenero) VALUES ('Prefiero no responder');

--TABLA PACIENTE

DROP TABLE IF EXISTS Paciente;
CREATE TABLE Paciente
(
Id INT IDENTITY NOT NULL,
Nombres VARCHAR(60) NOT NULL,
Apellidos VARCHAR(60) NOT NULL,
Genero INT NOt NULL,
Edad INT NOT NULL,
TipoSangre INT NOT NULL,
TipoRH INT NOT NULL

PRIMARY KEY(Id)

FOREIGN KEY (Genero) REFERENCES Genero(Id),
FOREIGN KEY (TipoSangre) REFERENCES TipoSangre(Id),
FOREIGN KEY (TipoRH) REFERENCES TipoRH(Id)
);

--DBCC CHECKIDENT ('TipoSangre', RESEED, 0)
