USE master
GO

--ELIMINA LA BASE DE DATOS SI YA EXISTE

IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = 'BaseGestionBDS')
BEGIN
	ALTER DATABASE [BaseGestionBDS] SET OFFLINE WITH ROLLBACK IMMEDIATE;
	ALTER DATABASE [BaseGestionBDS] SET ONLINE;
	DROP DATABASE [BaseGestionBDS];
END

GO

--CREANDO LA BASE DE DATOS

CREATE DATABASE BaseGestionBDS
GO

USE BaseGestionBDS
GO

--TABLA TIPOS DE SANGRE

DROP TABLE IF EXISTS Tipos_Sangre;
CREATE TABLE Tipos_Sangre
(
ID_TipoSangre VARCHAR(8) NOT NULL,
NombreTS VARCHAR(8) NOT NULL

PRIMARY KEY (ID_TipoSangre)

);

--TABLA TIPOS DE RH

DROP TABLE IF EXISTS Tipo_RH;
CREATE TABLE Tipo_RH
(
ID_TipoRH VARCHAR(8) NOT NULL,
NombreRH VARCHAR(8) NOT NULL

PRIMARY KEY (ID_TipoRH)

);

--TABLA PACIENTE

DROP TABLE IF EXISTS Paciente;
CREATE TABLE Paciente
(
ID_Paciente VARCHAR(6) NOT NULL,
Nombres_Paciente VARCHAR(60) NOT NULL,
Apellidos_Paciente VARCHAR(60) NOT NULL,
Genero_Paciente VARCHAR(10) NOt NULL,
Edad_Paciente INT NOT NULL,
Tipo_SangrePaciente VARCHAR(8) NOT NULL,
RH_Paciente VARCHAR(8) NOT NULL

PRIMARY KEY(ID_Paciente)

FOREIGN KEY (Tipo_SangrePaciente) REFERENCES Tipos_Sangre(ID_TipoSangre),
FOREIGN KEY (RH_Paciente) REFERENCES Tipo_RH(ID_TipoRH)
);


