USE master
GO

--ELIMINA LA BASE DE DATOS SI YA EXISTE

IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = 'BaseGestionBDS')
BEGIN
	ALTER DATABASE [BaseGestionBDS] SET OFFLINE WITH ROLLBACK IMMEDIATE;
	ALTER DATABASE [BaseGestionBDS] SET ONLINE;
	DROP DATABASE [BaseGestionBDS];
END

GO

--CREANDO LA BASE DE DATOS

CREATE DATABASE BaseGestionBDS
GO

USE BaseGestionBDS
GO

--TABLA TIPOS DE SANGRE

DROP TABLE IF EXISTS TipoSangre;
CREATE TABLE TipoSangre
(
Id INT IDENTITY NOT NULL,
NombreTS TEXT NOT NULL

PRIMARY KEY (Id)
);

--TABLA TIPOS DE RH

DROP TABLE IF EXISTS TipoRH;
CREATE TABLE TipoRH
(
Id INT IDENTITY NOT NULL,
NombreRH TEXT NOT NULL

PRIMARY KEY (Id)
);

--TABLA PACIENTE

DROP TABLE IF EXISTS Paciente;
CREATE TABLE Paciente
(
Id INT IDENTITY NOT NULL,
Nombres_Paciente VARCHAR(60) NOT NULL,
Apellidos_Paciente VARCHAR(60) NOT NULL,
Genero_Paciente VARCHAR(10) NOt NULL,
Edad_Paciente INT NOT NULL,
Tipo_SangrePaciente INT NOT NULL,
RH_Paciente INT NOT NULL

PRIMARY KEY(Id)

FOREIGN KEY (Tipo_SangrePaciente) REFERENCES TipoSangre(Id),
FOREIGN KEY (RH_Paciente) REFERENCES TipoRH(Id)
);

--DBCC CHECKIDENT ('TipoSangre', RESEED, 0)
